101-compile

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,2 +1,15 @@
 #!/bin/bash
-python3 -m compileall $PYFILE -b
+
+# Check if the PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable not set."
+    exit 1
+fi
+
+# Compile the Python script
+python -m py_compile "$PYFILE"
+
+# Output filename will be ${PYFILE}c
+compiled_filename="${PYFILE}c"
+
+echo "Compilation successful. Output filename: $compiled_filename"
